//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SAM.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(JuntaInspeccionVisual))]
    [KnownType(typeof(JuntaReportePnd))]
    [KnownType(typeof(JuntaReporteTt))]
    [KnownType(typeof(JuntaRequisicion))]
    [KnownType(typeof(JuntaSoldadura))]
    [KnownType(typeof(OrdenTrabajoSpool))]
    [KnownType(typeof(EstimacionJunta))]
    [KnownType(typeof(InspeccionVisualPatio))]
    [KnownType(typeof(UltimoProceso))]
    [KnownType(typeof(JuntaWorkstatus))]
    [KnownType(typeof(DestajoSoldadorDetalle))]
    [KnownType(typeof(DestajoTuberoDetalle))]
    [KnownType(typeof(JuntaArmado))]
    [KnownType(typeof(JuntaSpool))]
    [Serializable]
    public partial class JuntaWorkstatus: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int JuntaWorkstatusID
        {
            get { return _juntaWorkstatusID; }
            set
            {
                if (_juntaWorkstatusID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'JuntaWorkstatusID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _juntaWorkstatusID = value;
                    OnPropertyChanged("JuntaWorkstatusID");
                }
            }
        }
        private int _juntaWorkstatusID;
    
        [DataMember]
        public int OrdenTrabajoSpoolID
        {
            get { return _ordenTrabajoSpoolID; }
            set
            {
                if (_ordenTrabajoSpoolID != value)
                {
                    ChangeTracker.RecordOriginalValue("OrdenTrabajoSpoolID", _ordenTrabajoSpoolID);
                    if (!IsDeserializing)
                    {
                        if (OrdenTrabajoSpool != null && OrdenTrabajoSpool.OrdenTrabajoSpoolID != value)
                        {
                            OrdenTrabajoSpool = null;
                        }
                    }
                    _ordenTrabajoSpoolID = value;
                    OnPropertyChanged("OrdenTrabajoSpoolID");
                }
            }
        }
        private int _ordenTrabajoSpoolID;
    
        [DataMember]
        public int JuntaSpoolID
        {
            get { return _juntaSpoolID; }
            set
            {
                if (_juntaSpoolID != value)
                {
                    ChangeTracker.RecordOriginalValue("JuntaSpoolID", _juntaSpoolID);
                    if (!IsDeserializing)
                    {
                        if (JuntaSpool != null && JuntaSpool.JuntaSpoolID != value)
                        {
                            JuntaSpool = null;
                        }
                    }
                    _juntaSpoolID = value;
                    OnPropertyChanged("JuntaSpoolID");
                }
            }
        }
        private int _juntaSpoolID;
    
        [DataMember]
        public string EtiquetaJunta
        {
            get { return _etiquetaJunta; }
            set
            {
                if (_etiquetaJunta != value)
                {
                    _etiquetaJunta = value;
                    OnPropertyChanged("EtiquetaJunta");
                }
            }
        }
        private string _etiquetaJunta;
    
        [DataMember]
        public bool ArmadoAprobado
        {
            get { return _armadoAprobado; }
            set
            {
                if (_armadoAprobado != value)
                {
                    _armadoAprobado = value;
                    OnPropertyChanged("ArmadoAprobado");
                }
            }
        }
        private bool _armadoAprobado;
    
        [DataMember]
        public bool SoldaduraAprobada
        {
            get { return _soldaduraAprobada; }
            set
            {
                if (_soldaduraAprobada != value)
                {
                    _soldaduraAprobada = value;
                    OnPropertyChanged("SoldaduraAprobada");
                }
            }
        }
        private bool _soldaduraAprobada;
    
        [DataMember]
        public bool InspeccionVisualAprobada
        {
            get { return _inspeccionVisualAprobada; }
            set
            {
                if (_inspeccionVisualAprobada != value)
                {
                    _inspeccionVisualAprobada = value;
                    OnPropertyChanged("InspeccionVisualAprobada");
                }
            }
        }
        private bool _inspeccionVisualAprobada;
    
        [DataMember]
        public Nullable<int> JuntaArmadoID
        {
            get { return _juntaArmadoID; }
            set
            {
                if (_juntaArmadoID != value)
                {
                    ChangeTracker.RecordOriginalValue("JuntaArmadoID", _juntaArmadoID);
                    if (!IsDeserializing)
                    {
                        if (JuntaArmado1 != null && JuntaArmado1.JuntaArmadoID != value)
                        {
                            JuntaArmado1 = null;
                        }
                    }
                    _juntaArmadoID = value;
                    OnPropertyChanged("JuntaArmadoID");
                }
            }
        }
        private Nullable<int> _juntaArmadoID;
    
        [DataMember]
        public Nullable<int> JuntaSoldaduraID
        {
            get { return _juntaSoldaduraID; }
            set
            {
                if (_juntaSoldaduraID != value)
                {
                    ChangeTracker.RecordOriginalValue("JuntaSoldaduraID", _juntaSoldaduraID);
                    if (!IsDeserializing)
                    {
                        if (Soldadura != null && Soldadura.JuntaSoldaduraID != value)
                        {
                            Soldadura = null;
                        }
                    }
                    _juntaSoldaduraID = value;
                    OnPropertyChanged("JuntaSoldaduraID");
                }
            }
        }
        private Nullable<int> _juntaSoldaduraID;
    
        [DataMember]
        public Nullable<int> JuntaInspeccionVisualID
        {
            get { return _juntaInspeccionVisualID; }
            set
            {
                if (_juntaInspeccionVisualID != value)
                {
                    ChangeTracker.RecordOriginalValue("JuntaInspeccionVisualID", _juntaInspeccionVisualID);
                    if (!IsDeserializing)
                    {
                        if (InspeccionVisual != null && InspeccionVisual.JuntaInspeccionVisualID != value)
                        {
                            InspeccionVisual = null;
                        }
                    }
                    _juntaInspeccionVisualID = value;
                    OnPropertyChanged("JuntaInspeccionVisualID");
                }
            }
        }
        private Nullable<int> _juntaInspeccionVisualID;
    
        [DataMember]
        public int VersionJunta
        {
            get { return _versionJunta; }
            set
            {
                if (_versionJunta != value)
                {
                    _versionJunta = value;
                    OnPropertyChanged("VersionJunta");
                }
            }
        }
        private int _versionJunta;
    
        [DataMember]
        public Nullable<int> JuntaWorkstatusAnteriorID
        {
            get { return _juntaWorkstatusAnteriorID; }
            set
            {
                if (_juntaWorkstatusAnteriorID != value)
                {
                    ChangeTracker.RecordOriginalValue("JuntaWorkstatusAnteriorID", _juntaWorkstatusAnteriorID);
                    if (!IsDeserializing)
                    {
                        if (JuntaPadre != null && JuntaPadre.JuntaWorkstatusID != value)
                        {
                            JuntaPadre = null;
                        }
                    }
                    _juntaWorkstatusAnteriorID = value;
                    OnPropertyChanged("JuntaWorkstatusAnteriorID");
                }
            }
        }
        private Nullable<int> _juntaWorkstatusAnteriorID;
    
        [DataMember]
        public bool JuntaFinal
        {
            get { return _juntaFinal; }
            set
            {
                if (_juntaFinal != value)
                {
                    _juntaFinal = value;
                    OnPropertyChanged("JuntaFinal");
                }
            }
        }
        private bool _juntaFinal;
    
        [DataMember]
        public Nullable<System.Guid> UsuarioModifica
        {
            get { return _usuarioModifica; }
            set
            {
                if (_usuarioModifica != value)
                {
                    _usuarioModifica = value;
                    OnPropertyChanged("UsuarioModifica");
                }
            }
        }
        private Nullable<System.Guid> _usuarioModifica;
    
        [DataMember]
        public Nullable<System.DateTime> FechaModificacion
        {
            get { return _fechaModificacion; }
            set
            {
                if (_fechaModificacion != value)
                {
                    _fechaModificacion = value;
                    OnPropertyChanged("FechaModificacion");
                }
            }
        }
        private Nullable<System.DateTime> _fechaModificacion;
    
        [DataMember]
        public byte[] VersionRegistro
        {
            get { return _versionRegistro; }
            set
            {
                if (_versionRegistro != value)
                {
                    ChangeTracker.RecordOriginalValue("VersionRegistro", _versionRegistro);
                    _versionRegistro = value;
                    OnPropertyChanged("VersionRegistro");
                }
            }
        }
        private byte[] _versionRegistro;
    
        [DataMember]
        public Nullable<int> UltimoProcesoID
        {
            get { return _ultimoProcesoID; }
            set
            {
                if (_ultimoProcesoID != value)
                {
                    ChangeTracker.RecordOriginalValue("UltimoProcesoID", _ultimoProcesoID);
                    if (!IsDeserializing)
                    {
                        if (UltimoProceso != null && UltimoProceso.UltimoProcesoID != value)
                        {
                            UltimoProceso = null;
                        }
                    }
                    _ultimoProcesoID = value;
                    OnPropertyChanged("UltimoProcesoID");
                }
            }
        }
        private Nullable<int> _ultimoProcesoID;
    
        [DataMember]
        public Nullable<decimal> TotalPagado
        {
            get { return _totalPagado; }
            set
            {
                if (_totalPagado != value)
                {
                    _totalPagado = value;
                    OnPropertyChanged("TotalPagado");
                }
            }
        }
        private Nullable<decimal> _totalPagado;
    
        [DataMember]
        public bool ArmadoPagado
        {
            get { return _armadoPagado; }
            set
            {
                if (_armadoPagado != value)
                {
                    _armadoPagado = value;
                    OnPropertyChanged("ArmadoPagado");
                }
            }
        }
        private bool _armadoPagado;
    
        [DataMember]
        public bool SoldaduraPagada
        {
            get { return _soldaduraPagada; }
            set
            {
                if (_soldaduraPagada != value)
                {
                    _soldaduraPagada = value;
                    OnPropertyChanged("SoldaduraPagada");
                }
            }
        }
        private bool _soldaduraPagada;
    
        [DataMember]
        public Nullable<decimal> TotalPagadoArmado
        {
            get { return _totalPagadoArmado; }
            set
            {
                if (_totalPagadoArmado != value)
                {
                    _totalPagadoArmado = value;
                    OnPropertyChanged("TotalPagadoArmado");
                }
            }
        }
        private Nullable<decimal> _totalPagadoArmado;
    
        [DataMember]
        public Nullable<decimal> TotalPagadoSoldadura
        {
            get { return _totalPagadoSoldadura; }
            set
            {
                if (_totalPagadoSoldadura != value)
                {
                    _totalPagadoSoldadura = value;
                    OnPropertyChanged("TotalPagadoSoldadura");
                }
            }
        }
        private Nullable<decimal> _totalPagadoSoldadura;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<JuntaInspeccionVisual> JuntasInspeccionadas
        {
            get
            {
                if (_juntasInspeccionadas == null)
                {
                    _juntasInspeccionadas = new TrackableCollection<JuntaInspeccionVisual>();
                    _juntasInspeccionadas.CollectionChanged += FixupJuntasInspeccionadas;
                }
                return _juntasInspeccionadas;
            }
            set
            {
                if (!ReferenceEquals(_juntasInspeccionadas, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_juntasInspeccionadas != null)
                    {
                        _juntasInspeccionadas.CollectionChanged -= FixupJuntasInspeccionadas;
                    }
                    _juntasInspeccionadas = value;
                    if (_juntasInspeccionadas != null)
                    {
                        _juntasInspeccionadas.CollectionChanged += FixupJuntasInspeccionadas;
                    }
                    OnNavigationPropertyChanged("JuntasInspeccionadas");
                }
            }
        }
        private TrackableCollection<JuntaInspeccionVisual> _juntasInspeccionadas;
    
        [DataMember]
        public JuntaInspeccionVisual InspeccionVisual
        {
            get { return _inspeccionVisual; }
            set
            {
                if (!ReferenceEquals(_inspeccionVisual, value))
                {
                    var previousValue = _inspeccionVisual;
                    _inspeccionVisual = value;
                    FixupInspeccionVisual(previousValue);
                    OnNavigationPropertyChanged("InspeccionVisual");
                }
            }
        }
        private JuntaInspeccionVisual _inspeccionVisual;
    
        [DataMember]
        public TrackableCollection<JuntaReportePnd> JuntaReportePnd
        {
            get
            {
                if (_juntaReportePnd == null)
                {
                    _juntaReportePnd = new TrackableCollection<JuntaReportePnd>();
                    _juntaReportePnd.CollectionChanged += FixupJuntaReportePnd;
                }
                return _juntaReportePnd;
            }
            set
            {
                if (!ReferenceEquals(_juntaReportePnd, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_juntaReportePnd != null)
                    {
                        _juntaReportePnd.CollectionChanged -= FixupJuntaReportePnd;
                    }
                    _juntaReportePnd = value;
                    if (_juntaReportePnd != null)
                    {
                        _juntaReportePnd.CollectionChanged += FixupJuntaReportePnd;
                    }
                    OnNavigationPropertyChanged("JuntaReportePnd");
                }
            }
        }
        private TrackableCollection<JuntaReportePnd> _juntaReportePnd;
    
        [DataMember]
        public TrackableCollection<JuntaReporteTt> JuntaReporteTt
        {
            get
            {
                if (_juntaReporteTt == null)
                {
                    _juntaReporteTt = new TrackableCollection<JuntaReporteTt>();
                    _juntaReporteTt.CollectionChanged += FixupJuntaReporteTt;
                }
                return _juntaReporteTt;
            }
            set
            {
                if (!ReferenceEquals(_juntaReporteTt, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_juntaReporteTt != null)
                    {
                        _juntaReporteTt.CollectionChanged -= FixupJuntaReporteTt;
                    }
                    _juntaReporteTt = value;
                    if (_juntaReporteTt != null)
                    {
                        _juntaReporteTt.CollectionChanged += FixupJuntaReporteTt;
                    }
                    OnNavigationPropertyChanged("JuntaReporteTt");
                }
            }
        }
        private TrackableCollection<JuntaReporteTt> _juntaReporteTt;
    
        [DataMember]
        public TrackableCollection<JuntaRequisicion> JuntaRequisicion
        {
            get
            {
                if (_juntaRequisicion == null)
                {
                    _juntaRequisicion = new TrackableCollection<JuntaRequisicion>();
                    _juntaRequisicion.CollectionChanged += FixupJuntaRequisicion;
                }
                return _juntaRequisicion;
            }
            set
            {
                if (!ReferenceEquals(_juntaRequisicion, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_juntaRequisicion != null)
                    {
                        _juntaRequisicion.CollectionChanged -= FixupJuntaRequisicion;
                    }
                    _juntaRequisicion = value;
                    if (_juntaRequisicion != null)
                    {
                        _juntaRequisicion.CollectionChanged += FixupJuntaRequisicion;
                    }
                    OnNavigationPropertyChanged("JuntaRequisicion");
                }
            }
        }
        private TrackableCollection<JuntaRequisicion> _juntaRequisicion;
    
        [DataMember]
        public TrackableCollection<JuntaSoldadura> JuntasSoldadas
        {
            get
            {
                if (_juntasSoldadas == null)
                {
                    _juntasSoldadas = new TrackableCollection<JuntaSoldadura>();
                    _juntasSoldadas.CollectionChanged += FixupJuntasSoldadas;
                }
                return _juntasSoldadas;
            }
            set
            {
                if (!ReferenceEquals(_juntasSoldadas, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_juntasSoldadas != null)
                    {
                        _juntasSoldadas.CollectionChanged -= FixupJuntasSoldadas;
                    }
                    _juntasSoldadas = value;
                    if (_juntasSoldadas != null)
                    {
                        _juntasSoldadas.CollectionChanged += FixupJuntasSoldadas;
                    }
                    OnNavigationPropertyChanged("JuntasSoldadas");
                }
            }
        }
        private TrackableCollection<JuntaSoldadura> _juntasSoldadas;
    
        [DataMember]
        public JuntaSoldadura Soldadura
        {
            get { return _soldadura; }
            set
            {
                if (!ReferenceEquals(_soldadura, value))
                {
                    var previousValue = _soldadura;
                    _soldadura = value;
                    FixupSoldadura(previousValue);
                    OnNavigationPropertyChanged("Soldadura");
                }
            }
        }
        private JuntaSoldadura _soldadura;
    
        [DataMember]
        public OrdenTrabajoSpool OrdenTrabajoSpool
        {
            get { return _ordenTrabajoSpool; }
            set
            {
                if (!ReferenceEquals(_ordenTrabajoSpool, value))
                {
                    var previousValue = _ordenTrabajoSpool;
                    _ordenTrabajoSpool = value;
                    FixupOrdenTrabajoSpool(previousValue);
                    OnNavigationPropertyChanged("OrdenTrabajoSpool");
                }
            }
        }
        private OrdenTrabajoSpool _ordenTrabajoSpool;
    
        [DataMember]
        public TrackableCollection<EstimacionJunta> EstimacionJunta
        {
            get
            {
                if (_estimacionJunta == null)
                {
                    _estimacionJunta = new TrackableCollection<EstimacionJunta>();
                    _estimacionJunta.CollectionChanged += FixupEstimacionJunta;
                }
                return _estimacionJunta;
            }
            set
            {
                if (!ReferenceEquals(_estimacionJunta, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_estimacionJunta != null)
                    {
                        _estimacionJunta.CollectionChanged -= FixupEstimacionJunta;
                    }
                    _estimacionJunta = value;
                    if (_estimacionJunta != null)
                    {
                        _estimacionJunta.CollectionChanged += FixupEstimacionJunta;
                    }
                    OnNavigationPropertyChanged("EstimacionJunta");
                }
            }
        }
        private TrackableCollection<EstimacionJunta> _estimacionJunta;
    
        [DataMember]
        public TrackableCollection<InspeccionVisualPatio> InspeccionVisualPatio
        {
            get
            {
                if (_inspeccionVisualPatio == null)
                {
                    _inspeccionVisualPatio = new TrackableCollection<InspeccionVisualPatio>();
                    _inspeccionVisualPatio.CollectionChanged += FixupInspeccionVisualPatio;
                }
                return _inspeccionVisualPatio;
            }
            set
            {
                if (!ReferenceEquals(_inspeccionVisualPatio, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_inspeccionVisualPatio != null)
                    {
                        _inspeccionVisualPatio.CollectionChanged -= FixupInspeccionVisualPatio;
                    }
                    _inspeccionVisualPatio = value;
                    if (_inspeccionVisualPatio != null)
                    {
                        _inspeccionVisualPatio.CollectionChanged += FixupInspeccionVisualPatio;
                    }
                    OnNavigationPropertyChanged("InspeccionVisualPatio");
                }
            }
        }
        private TrackableCollection<InspeccionVisualPatio> _inspeccionVisualPatio;
    
        [DataMember]
        public UltimoProceso UltimoProceso
        {
            get { return _ultimoProceso; }
            set
            {
                if (!ReferenceEquals(_ultimoProceso, value))
                {
                    var previousValue = _ultimoProceso;
                    _ultimoProceso = value;
                    FixupUltimoProceso(previousValue);
                    OnNavigationPropertyChanged("UltimoProceso");
                }
            }
        }
        private UltimoProceso _ultimoProceso;
    
        [DataMember]
        public TrackableCollection<JuntaWorkstatus> JuntasHijas
        {
            get
            {
                if (_juntasHijas == null)
                {
                    _juntasHijas = new TrackableCollection<JuntaWorkstatus>();
                    _juntasHijas.CollectionChanged += FixupJuntasHijas;
                }
                return _juntasHijas;
            }
            set
            {
                if (!ReferenceEquals(_juntasHijas, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_juntasHijas != null)
                    {
                        _juntasHijas.CollectionChanged -= FixupJuntasHijas;
                    }
                    _juntasHijas = value;
                    if (_juntasHijas != null)
                    {
                        _juntasHijas.CollectionChanged += FixupJuntasHijas;
                    }
                    OnNavigationPropertyChanged("JuntasHijas");
                }
            }
        }
        private TrackableCollection<JuntaWorkstatus> _juntasHijas;
    
        [DataMember]
        public JuntaWorkstatus JuntaPadre
        {
            get { return _juntaPadre; }
            set
            {
                if (!ReferenceEquals(_juntaPadre, value))
                {
                    var previousValue = _juntaPadre;
                    _juntaPadre = value;
                    FixupJuntaPadre(previousValue);
                    OnNavigationPropertyChanged("JuntaPadre");
                }
            }
        }
        private JuntaWorkstatus _juntaPadre;
    
        [DataMember]
        public TrackableCollection<DestajoSoldadorDetalle> DestajoSoldadorDetalle
        {
            get
            {
                if (_destajoSoldadorDetalle == null)
                {
                    _destajoSoldadorDetalle = new TrackableCollection<DestajoSoldadorDetalle>();
                    _destajoSoldadorDetalle.CollectionChanged += FixupDestajoSoldadorDetalle;
                }
                return _destajoSoldadorDetalle;
            }
            set
            {
                if (!ReferenceEquals(_destajoSoldadorDetalle, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_destajoSoldadorDetalle != null)
                    {
                        _destajoSoldadorDetalle.CollectionChanged -= FixupDestajoSoldadorDetalle;
                    }
                    _destajoSoldadorDetalle = value;
                    if (_destajoSoldadorDetalle != null)
                    {
                        _destajoSoldadorDetalle.CollectionChanged += FixupDestajoSoldadorDetalle;
                    }
                    OnNavigationPropertyChanged("DestajoSoldadorDetalle");
                }
            }
        }
        private TrackableCollection<DestajoSoldadorDetalle> _destajoSoldadorDetalle;
    
        [DataMember]
        public TrackableCollection<DestajoTuberoDetalle> DestajoTuberoDetalle
        {
            get
            {
                if (_destajoTuberoDetalle == null)
                {
                    _destajoTuberoDetalle = new TrackableCollection<DestajoTuberoDetalle>();
                    _destajoTuberoDetalle.CollectionChanged += FixupDestajoTuberoDetalle;
                }
                return _destajoTuberoDetalle;
            }
            set
            {
                if (!ReferenceEquals(_destajoTuberoDetalle, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_destajoTuberoDetalle != null)
                    {
                        _destajoTuberoDetalle.CollectionChanged -= FixupDestajoTuberoDetalle;
                    }
                    _destajoTuberoDetalle = value;
                    if (_destajoTuberoDetalle != null)
                    {
                        _destajoTuberoDetalle.CollectionChanged += FixupDestajoTuberoDetalle;
                    }
                    OnNavigationPropertyChanged("DestajoTuberoDetalle");
                }
            }
        }
        private TrackableCollection<DestajoTuberoDetalle> _destajoTuberoDetalle;
    
        [DataMember]
        public TrackableCollection<JuntaArmado> JuntaArmado
        {
            get
            {
                if (_juntaArmado == null)
                {
                    _juntaArmado = new TrackableCollection<JuntaArmado>();
                    _juntaArmado.CollectionChanged += FixupJuntaArmado;
                }
                return _juntaArmado;
            }
            set
            {
                if (!ReferenceEquals(_juntaArmado, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_juntaArmado != null)
                    {
                        _juntaArmado.CollectionChanged -= FixupJuntaArmado;
                    }
                    _juntaArmado = value;
                    if (_juntaArmado != null)
                    {
                        _juntaArmado.CollectionChanged += FixupJuntaArmado;
                    }
                    OnNavigationPropertyChanged("JuntaArmado");
                }
            }
        }
        private TrackableCollection<JuntaArmado> _juntaArmado;
    
        [DataMember]
        public JuntaArmado JuntaArmado1
        {
            get { return _juntaArmado1; }
            set
            {
                if (!ReferenceEquals(_juntaArmado1, value))
                {
                    var previousValue = _juntaArmado1;
                    _juntaArmado1 = value;
                    FixupJuntaArmado1(previousValue);
                    OnNavigationPropertyChanged("JuntaArmado1");
                }
            }
        }
        private JuntaArmado _juntaArmado1;
    
        [DataMember]
        public JuntaSpool JuntaSpool
        {
            get { return _juntaSpool; }
            set
            {
                if (!ReferenceEquals(_juntaSpool, value))
                {
                    var previousValue = _juntaSpool;
                    _juntaSpool = value;
                    FixupJuntaSpool(previousValue);
                    OnNavigationPropertyChanged("JuntaSpool");
                }
            }
        }
        private JuntaSpool _juntaSpool;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
    	public void OnDeserializedMethod(StreamingContext context)
    	{
    		IsDeserializing = false;
    		ChangeTracker.ChangeTrackingEnabled = true;
    			if (_juntasInspeccionadas != null)
    		{
    			_juntasInspeccionadas.CollectionChanged -= FixupJuntasInspeccionadas;
    			_juntasInspeccionadas.CollectionChanged += FixupJuntasInspeccionadas;
    			}
    			if (_juntaReportePnd != null)
    		{
    			_juntaReportePnd.CollectionChanged -= FixupJuntaReportePnd;
    			_juntaReportePnd.CollectionChanged += FixupJuntaReportePnd;
    			}
    			if (_juntaReporteTt != null)
    		{
    			_juntaReporteTt.CollectionChanged -= FixupJuntaReporteTt;
    			_juntaReporteTt.CollectionChanged += FixupJuntaReporteTt;
    			}
    			if (_juntaRequisicion != null)
    		{
    			_juntaRequisicion.CollectionChanged -= FixupJuntaRequisicion;
    			_juntaRequisicion.CollectionChanged += FixupJuntaRequisicion;
    			}
    			if (_juntasSoldadas != null)
    		{
    			_juntasSoldadas.CollectionChanged -= FixupJuntasSoldadas;
    			_juntasSoldadas.CollectionChanged += FixupJuntasSoldadas;
    			}
    			if (_estimacionJunta != null)
    		{
    			_estimacionJunta.CollectionChanged -= FixupEstimacionJunta;
    			_estimacionJunta.CollectionChanged += FixupEstimacionJunta;
    			}
    			if (_inspeccionVisualPatio != null)
    		{
    			_inspeccionVisualPatio.CollectionChanged -= FixupInspeccionVisualPatio;
    			_inspeccionVisualPatio.CollectionChanged += FixupInspeccionVisualPatio;
    			}
    			if (_juntasHijas != null)
    		{
    			_juntasHijas.CollectionChanged -= FixupJuntasHijas;
    			_juntasHijas.CollectionChanged += FixupJuntasHijas;
    			}
    			if (_destajoSoldadorDetalle != null)
    		{
    			_destajoSoldadorDetalle.CollectionChanged -= FixupDestajoSoldadorDetalle;
    			_destajoSoldadorDetalle.CollectionChanged += FixupDestajoSoldadorDetalle;
    			}
    			if (_destajoTuberoDetalle != null)
    		{
    			_destajoTuberoDetalle.CollectionChanged -= FixupDestajoTuberoDetalle;
    			_destajoTuberoDetalle.CollectionChanged += FixupDestajoTuberoDetalle;
    			}
    			if (_juntaArmado != null)
    		{
    			_juntaArmado.CollectionChanged -= FixupJuntaArmado;
    			_juntaArmado.CollectionChanged += FixupJuntaArmado;
    			}
    		}
    
    
        protected virtual void ClearNavigationProperties()
        {
            JuntasInspeccionadas.Clear();
            InspeccionVisual = null;
            JuntaReportePnd.Clear();
            JuntaReporteTt.Clear();
            JuntaRequisicion.Clear();
            JuntasSoldadas.Clear();
            Soldadura = null;
            OrdenTrabajoSpool = null;
            EstimacionJunta.Clear();
            InspeccionVisualPatio.Clear();
            UltimoProceso = null;
            JuntasHijas.Clear();
            JuntaPadre = null;
            DestajoSoldadorDetalle.Clear();
            DestajoTuberoDetalle.Clear();
            JuntaArmado.Clear();
            JuntaArmado1 = null;
            JuntaSpool = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupInspeccionVisual(JuntaInspeccionVisual previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.JuntasWorkstatus.Contains(this))
            {
                previousValue.JuntasWorkstatus.Remove(this);
            }
    
            if (InspeccionVisual != null)
            {
                if (!InspeccionVisual.JuntasWorkstatus.Contains(this))
                {
                    InspeccionVisual.JuntasWorkstatus.Add(this);
                }
    
                JuntaInspeccionVisualID = InspeccionVisual.JuntaInspeccionVisualID;
            }
            else if (!skipKeys)
            {
                JuntaInspeccionVisualID = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("InspeccionVisual")
                    && (ChangeTracker.OriginalValues["InspeccionVisual"] == InspeccionVisual))
                {
                    ChangeTracker.OriginalValues.Remove("InspeccionVisual");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("InspeccionVisual", previousValue);
                }
                if (InspeccionVisual != null && !InspeccionVisual.ChangeTracker.ChangeTrackingEnabled)
                {
                    InspeccionVisual.StartTracking();
                }
            }
        }
    
        private void FixupSoldadura(JuntaSoldadura previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.JuntaWorkstatus1.Contains(this))
            {
                previousValue.JuntaWorkstatus1.Remove(this);
            }
    
            if (Soldadura != null)
            {
                if (!Soldadura.JuntaWorkstatus1.Contains(this))
                {
                    Soldadura.JuntaWorkstatus1.Add(this);
                }
    
                JuntaSoldaduraID = Soldadura.JuntaSoldaduraID;
            }
            else if (!skipKeys)
            {
                JuntaSoldaduraID = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Soldadura")
                    && (ChangeTracker.OriginalValues["Soldadura"] == Soldadura))
                {
                    ChangeTracker.OriginalValues.Remove("Soldadura");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Soldadura", previousValue);
                }
                if (Soldadura != null && !Soldadura.ChangeTracker.ChangeTrackingEnabled)
                {
                    Soldadura.StartTracking();
                }
            }
        }
    
        private void FixupOrdenTrabajoSpool(OrdenTrabajoSpool previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.JuntaWorkstatus.Contains(this))
            {
                previousValue.JuntaWorkstatus.Remove(this);
            }
    
            if (OrdenTrabajoSpool != null)
            {
                if (!OrdenTrabajoSpool.JuntaWorkstatus.Contains(this))
                {
                    OrdenTrabajoSpool.JuntaWorkstatus.Add(this);
                }
    
                OrdenTrabajoSpoolID = OrdenTrabajoSpool.OrdenTrabajoSpoolID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("OrdenTrabajoSpool")
                    && (ChangeTracker.OriginalValues["OrdenTrabajoSpool"] == OrdenTrabajoSpool))
                {
                    ChangeTracker.OriginalValues.Remove("OrdenTrabajoSpool");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("OrdenTrabajoSpool", previousValue);
                }
                if (OrdenTrabajoSpool != null && !OrdenTrabajoSpool.ChangeTracker.ChangeTrackingEnabled)
                {
                    OrdenTrabajoSpool.StartTracking();
                }
            }
        }
    
        private void FixupUltimoProceso(UltimoProceso previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.JuntaWorkstatus.Contains(this))
            {
                previousValue.JuntaWorkstatus.Remove(this);
            }
    
            if (UltimoProceso != null)
            {
                if (!UltimoProceso.JuntaWorkstatus.Contains(this))
                {
                    UltimoProceso.JuntaWorkstatus.Add(this);
                }
    
                UltimoProcesoID = UltimoProceso.UltimoProcesoID;
            }
            else if (!skipKeys)
            {
                UltimoProcesoID = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("UltimoProceso")
                    && (ChangeTracker.OriginalValues["UltimoProceso"] == UltimoProceso))
                {
                    ChangeTracker.OriginalValues.Remove("UltimoProceso");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("UltimoProceso", previousValue);
                }
                if (UltimoProceso != null && !UltimoProceso.ChangeTracker.ChangeTrackingEnabled)
                {
                    UltimoProceso.StartTracking();
                }
            }
        }
    
        private void FixupJuntaPadre(JuntaWorkstatus previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.JuntasHijas.Contains(this))
            {
                previousValue.JuntasHijas.Remove(this);
            }
    
            if (JuntaPadre != null)
            {
                if (!JuntaPadre.JuntasHijas.Contains(this))
                {
                    JuntaPadre.JuntasHijas.Add(this);
                }
    
                JuntaWorkstatusAnteriorID = JuntaPadre.JuntaWorkstatusID;
            }
            else if (!skipKeys)
            {
                JuntaWorkstatusAnteriorID = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("JuntaPadre")
                    && (ChangeTracker.OriginalValues["JuntaPadre"] == JuntaPadre))
                {
                    ChangeTracker.OriginalValues.Remove("JuntaPadre");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("JuntaPadre", previousValue);
                }
                if (JuntaPadre != null && !JuntaPadre.ChangeTracker.ChangeTrackingEnabled)
                {
                    JuntaPadre.StartTracking();
                }
            }
        }
    
        private void FixupJuntaArmado1(JuntaArmado previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.JuntaWorkstatus1.Contains(this))
            {
                previousValue.JuntaWorkstatus1.Remove(this);
            }
    
            if (JuntaArmado1 != null)
            {
                if (!JuntaArmado1.JuntaWorkstatus1.Contains(this))
                {
                    JuntaArmado1.JuntaWorkstatus1.Add(this);
                }
    
                JuntaArmadoID = JuntaArmado1.JuntaArmadoID;
            }
            else if (!skipKeys)
            {
                JuntaArmadoID = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("JuntaArmado1")
                    && (ChangeTracker.OriginalValues["JuntaArmado1"] == JuntaArmado1))
                {
                    ChangeTracker.OriginalValues.Remove("JuntaArmado1");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("JuntaArmado1", previousValue);
                }
                if (JuntaArmado1 != null && !JuntaArmado1.ChangeTracker.ChangeTrackingEnabled)
                {
                    JuntaArmado1.StartTracking();
                }
            }
        }
    
        private void FixupJuntaSpool(JuntaSpool previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.JuntaWorkstatus.Contains(this))
            {
                previousValue.JuntaWorkstatus.Remove(this);
            }
    
            if (JuntaSpool != null)
            {
                if (!JuntaSpool.JuntaWorkstatus.Contains(this))
                {
                    JuntaSpool.JuntaWorkstatus.Add(this);
                }
    
                JuntaSpoolID = JuntaSpool.JuntaSpoolID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("JuntaSpool")
                    && (ChangeTracker.OriginalValues["JuntaSpool"] == JuntaSpool))
                {
                    ChangeTracker.OriginalValues.Remove("JuntaSpool");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("JuntaSpool", previousValue);
                }
                if (JuntaSpool != null && !JuntaSpool.ChangeTracker.ChangeTrackingEnabled)
                {
                    JuntaSpool.StartTracking();
                }
            }
        }
    
        private void FixupJuntasInspeccionadas(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (JuntaInspeccionVisual item in e.NewItems)
                {
                    item.JuntaWorkstatus = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("JuntasInspeccionadas", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (JuntaInspeccionVisual item in e.OldItems)
                {
                    if (ReferenceEquals(item.JuntaWorkstatus, this))
                    {
                        item.JuntaWorkstatus = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("JuntasInspeccionadas", item);
                    }
                }
            }
        }
    
        private void FixupJuntaReportePnd(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (JuntaReportePnd item in e.NewItems)
                {
                    item.JuntaWorkstatus = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("JuntaReportePnd", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (JuntaReportePnd item in e.OldItems)
                {
                    if (ReferenceEquals(item.JuntaWorkstatus, this))
                    {
                        item.JuntaWorkstatus = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("JuntaReportePnd", item);
                    }
                }
            }
        }
    
        private void FixupJuntaReporteTt(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (JuntaReporteTt item in e.NewItems)
                {
                    item.JuntaWorkstatus = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("JuntaReporteTt", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (JuntaReporteTt item in e.OldItems)
                {
                    if (ReferenceEquals(item.JuntaWorkstatus, this))
                    {
                        item.JuntaWorkstatus = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("JuntaReporteTt", item);
                    }
                }
            }
        }
    
        private void FixupJuntaRequisicion(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (JuntaRequisicion item in e.NewItems)
                {
                    item.JuntaWorkstatus = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("JuntaRequisicion", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (JuntaRequisicion item in e.OldItems)
                {
                    if (ReferenceEquals(item.JuntaWorkstatus, this))
                    {
                        item.JuntaWorkstatus = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("JuntaRequisicion", item);
                    }
                }
            }
        }
    
        private void FixupJuntasSoldadas(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (JuntaSoldadura item in e.NewItems)
                {
                    item.JuntaWorkstatus = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("JuntasSoldadas", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (JuntaSoldadura item in e.OldItems)
                {
                    if (ReferenceEquals(item.JuntaWorkstatus, this))
                    {
                        item.JuntaWorkstatus = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("JuntasSoldadas", item);
                    }
                }
            }
        }
    
        private void FixupEstimacionJunta(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (EstimacionJunta item in e.NewItems)
                {
                    item.JuntaWorkstatus = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("EstimacionJunta", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (EstimacionJunta item in e.OldItems)
                {
                    if (ReferenceEquals(item.JuntaWorkstatus, this))
                    {
                        item.JuntaWorkstatus = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("EstimacionJunta", item);
                    }
                }
            }
        }
    
        private void FixupInspeccionVisualPatio(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (InspeccionVisualPatio item in e.NewItems)
                {
                    item.JuntaWorkstatus = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("InspeccionVisualPatio", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (InspeccionVisualPatio item in e.OldItems)
                {
                    if (ReferenceEquals(item.JuntaWorkstatus, this))
                    {
                        item.JuntaWorkstatus = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("InspeccionVisualPatio", item);
                    }
                }
            }
        }
    
        private void FixupJuntasHijas(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (JuntaWorkstatus item in e.NewItems)
                {
                    item.JuntaPadre = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("JuntasHijas", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (JuntaWorkstatus item in e.OldItems)
                {
                    if (ReferenceEquals(item.JuntaPadre, this))
                    {
                        item.JuntaPadre = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("JuntasHijas", item);
                    }
                }
            }
        }
    
        private void FixupDestajoSoldadorDetalle(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (DestajoSoldadorDetalle item in e.NewItems)
                {
                    item.JuntaWorkstatus = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("DestajoSoldadorDetalle", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (DestajoSoldadorDetalle item in e.OldItems)
                {
                    if (ReferenceEquals(item.JuntaWorkstatus, this))
                    {
                        item.JuntaWorkstatus = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("DestajoSoldadorDetalle", item);
                    }
                }
            }
        }
    
        private void FixupDestajoTuberoDetalle(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (DestajoTuberoDetalle item in e.NewItems)
                {
                    item.JuntaWorkstatus = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("DestajoTuberoDetalle", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (DestajoTuberoDetalle item in e.OldItems)
                {
                    if (ReferenceEquals(item.JuntaWorkstatus, this))
                    {
                        item.JuntaWorkstatus = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("DestajoTuberoDetalle", item);
                    }
                }
            }
        }
    
        private void FixupJuntaArmado(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (JuntaArmado item in e.NewItems)
                {
                    item.JuntaWorkstatus = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("JuntaArmado", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (JuntaArmado item in e.OldItems)
                {
                    if (ReferenceEquals(item.JuntaWorkstatus, this))
                    {
                        item.JuntaWorkstatus = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("JuntaArmado", item);
                    }
                }
            }
        }

        #endregion

    }
}
