//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SAM.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Defecto))]
    [KnownType(typeof(JuntaInspeccionVisual))]
    [Serializable]
    public partial class JuntaInspeccionVisualDefecto: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int JuntaInspeccionVisualDefectoID
        {
            get { return _juntaInspeccionVisualDefectoID; }
            set
            {
                if (_juntaInspeccionVisualDefectoID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'JuntaInspeccionVisualDefectoID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _juntaInspeccionVisualDefectoID = value;
                    OnPropertyChanged("JuntaInspeccionVisualDefectoID");
                }
            }
        }
        private int _juntaInspeccionVisualDefectoID;
    
        [DataMember]
        public int JuntaInspeccionVisualID
        {
            get { return _juntaInspeccionVisualID; }
            set
            {
                if (_juntaInspeccionVisualID != value)
                {
                    ChangeTracker.RecordOriginalValue("JuntaInspeccionVisualID", _juntaInspeccionVisualID);
                    if (!IsDeserializing)
                    {
                        if (JuntaInspeccionVisual != null && JuntaInspeccionVisual.JuntaInspeccionVisualID != value)
                        {
                            JuntaInspeccionVisual = null;
                        }
                    }
                    _juntaInspeccionVisualID = value;
                    OnPropertyChanged("JuntaInspeccionVisualID");
                }
            }
        }
        private int _juntaInspeccionVisualID;
    
        [DataMember]
        public int DefectoID
        {
            get { return _defectoID; }
            set
            {
                if (_defectoID != value)
                {
                    ChangeTracker.RecordOriginalValue("DefectoID", _defectoID);
                    if (!IsDeserializing)
                    {
                        if (Defecto != null && Defecto.DefectoID != value)
                        {
                            Defecto = null;
                        }
                    }
                    _defectoID = value;
                    OnPropertyChanged("DefectoID");
                }
            }
        }
        private int _defectoID;
    
        [DataMember]
        public Nullable<System.Guid> UsuarioModifica
        {
            get { return _usuarioModifica; }
            set
            {
                if (_usuarioModifica != value)
                {
                    _usuarioModifica = value;
                    OnPropertyChanged("UsuarioModifica");
                }
            }
        }
        private Nullable<System.Guid> _usuarioModifica;
    
        [DataMember]
        public Nullable<System.DateTime> FechaModificacion
        {
            get { return _fechaModificacion; }
            set
            {
                if (_fechaModificacion != value)
                {
                    _fechaModificacion = value;
                    OnPropertyChanged("FechaModificacion");
                }
            }
        }
        private Nullable<System.DateTime> _fechaModificacion;
    
        [DataMember]
        public byte[] VersionRegistro
        {
            get { return _versionRegistro; }
            set
            {
                if (_versionRegistro != value)
                {
                    ChangeTracker.RecordOriginalValue("VersionRegistro", _versionRegistro);
                    _versionRegistro = value;
                    OnPropertyChanged("VersionRegistro");
                }
            }
        }
        private byte[] _versionRegistro;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public Defecto Defecto
        {
            get { return _defecto; }
            set
            {
                if (!ReferenceEquals(_defecto, value))
                {
                    var previousValue = _defecto;
                    _defecto = value;
                    FixupDefecto(previousValue);
                    OnNavigationPropertyChanged("Defecto");
                }
            }
        }
        private Defecto _defecto;
    
        [DataMember]
        public JuntaInspeccionVisual JuntaInspeccionVisual
        {
            get { return _juntaInspeccionVisual; }
            set
            {
                if (!ReferenceEquals(_juntaInspeccionVisual, value))
                {
                    var previousValue = _juntaInspeccionVisual;
                    _juntaInspeccionVisual = value;
                    FixupJuntaInspeccionVisual(previousValue);
                    OnNavigationPropertyChanged("JuntaInspeccionVisual");
                }
            }
        }
        private JuntaInspeccionVisual _juntaInspeccionVisual;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
    	public void OnDeserializedMethod(StreamingContext context)
    	{
    		IsDeserializing = false;
    		ChangeTracker.ChangeTrackingEnabled = true;
    		}
    
    
        protected virtual void ClearNavigationProperties()
        {
            Defecto = null;
            JuntaInspeccionVisual = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupDefecto(Defecto previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.JuntaInspeccionVisualDefecto.Contains(this))
            {
                previousValue.JuntaInspeccionVisualDefecto.Remove(this);
            }
    
            if (Defecto != null)
            {
                if (!Defecto.JuntaInspeccionVisualDefecto.Contains(this))
                {
                    Defecto.JuntaInspeccionVisualDefecto.Add(this);
                }
    
                DefectoID = Defecto.DefectoID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Defecto")
                    && (ChangeTracker.OriginalValues["Defecto"] == Defecto))
                {
                    ChangeTracker.OriginalValues.Remove("Defecto");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Defecto", previousValue);
                }
                if (Defecto != null && !Defecto.ChangeTracker.ChangeTrackingEnabled)
                {
                    Defecto.StartTracking();
                }
            }
        }
    
        private void FixupJuntaInspeccionVisual(JuntaInspeccionVisual previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.JuntaInspeccionVisualDefecto.Contains(this))
            {
                previousValue.JuntaInspeccionVisualDefecto.Remove(this);
            }
    
            if (JuntaInspeccionVisual != null)
            {
                if (!JuntaInspeccionVisual.JuntaInspeccionVisualDefecto.Contains(this))
                {
                    JuntaInspeccionVisual.JuntaInspeccionVisualDefecto.Add(this);
                }
    
                JuntaInspeccionVisualID = JuntaInspeccionVisual.JuntaInspeccionVisualID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("JuntaInspeccionVisual")
                    && (ChangeTracker.OriginalValues["JuntaInspeccionVisual"] == JuntaInspeccionVisual))
                {
                    ChangeTracker.OriginalValues.Remove("JuntaInspeccionVisual");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("JuntaInspeccionVisual", previousValue);
                }
                if (JuntaInspeccionVisual != null && !JuntaInspeccionVisual.ChangeTracker.ChangeTrackingEnabled)
                {
                    JuntaInspeccionVisual.StartTracking();
                }
            }
        }

        #endregion

    }
}
