//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SAM.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(EstatusOrden))]
    [KnownType(typeof(Proyecto))]
    [KnownType(typeof(Taller))]
    [KnownType(typeof(OrdenTrabajoEspecialSpool))]
    [Serializable]
    public partial class OrdenTrabajoEspecial: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int OrdenTrabajoEspecialID
        {
            get { return _ordenTrabajoEspecialID; }
            set
            {
                if (_ordenTrabajoEspecialID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'OrdenTrabajoEspecialID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _ordenTrabajoEspecialID = value;
                    OnPropertyChanged("OrdenTrabajoEspecialID");
                }
            }
        }
        private int _ordenTrabajoEspecialID;
    
        [DataMember]
        public int EstatusOrdenID
        {
            get { return _estatusOrdenID; }
            set
            {
                if (_estatusOrdenID != value)
                {
                    ChangeTracker.RecordOriginalValue("EstatusOrdenID", _estatusOrdenID);
                    if (!IsDeserializing)
                    {
                        if (EstatusOrden != null && EstatusOrden.EstatusOrdenID != value)
                        {
                            EstatusOrden = null;
                        }
                    }
                    _estatusOrdenID = value;
                    OnPropertyChanged("EstatusOrdenID");
                }
            }
        }
        private int _estatusOrdenID;
    
        [DataMember]
        public int ProyectoID
        {
            get { return _proyectoID; }
            set
            {
                if (_proyectoID != value)
                {
                    ChangeTracker.RecordOriginalValue("ProyectoID", _proyectoID);
                    if (!IsDeserializing)
                    {
                        if (Proyecto != null && Proyecto.ProyectoID != value)
                        {
                            Proyecto = null;
                        }
                    }
                    _proyectoID = value;
                    OnPropertyChanged("ProyectoID");
                }
            }
        }
        private int _proyectoID;
    
        [DataMember]
        public int TallerID
        {
            get { return _tallerID; }
            set
            {
                if (_tallerID != value)
                {
                    ChangeTracker.RecordOriginalValue("TallerID", _tallerID);
                    if (!IsDeserializing)
                    {
                        if (Taller != null && Taller.TallerID != value)
                        {
                            Taller = null;
                        }
                    }
                    _tallerID = value;
                    OnPropertyChanged("TallerID");
                }
            }
        }
        private int _tallerID;
    
        [DataMember]
        public string NumeroOrden
        {
            get { return _numeroOrden; }
            set
            {
                if (_numeroOrden != value)
                {
                    _numeroOrden = value;
                    OnPropertyChanged("NumeroOrden");
                }
            }
        }
        private string _numeroOrden;
    
        [DataMember]
        public System.DateTime FechaOrden
        {
            get { return _fechaOrden; }
            set
            {
                if (_fechaOrden != value)
                {
                    _fechaOrden = value;
                    OnPropertyChanged("FechaOrden");
                }
            }
        }
        private System.DateTime _fechaOrden;
    
        [DataMember]
        public Nullable<System.Guid> UsuarioModifica
        {
            get { return _usuarioModifica; }
            set
            {
                if (_usuarioModifica != value)
                {
                    _usuarioModifica = value;
                    OnPropertyChanged("UsuarioModifica");
                }
            }
        }
        private Nullable<System.Guid> _usuarioModifica;
    
        [DataMember]
        public Nullable<System.DateTime> FechaModificacion
        {
            get { return _fechaModificacion; }
            set
            {
                if (_fechaModificacion != value)
                {
                    _fechaModificacion = value;
                    OnPropertyChanged("FechaModificacion");
                }
            }
        }
        private Nullable<System.DateTime> _fechaModificacion;
    
        [DataMember]
        public byte[] VersionRegistro
        {
            get { return _versionRegistro; }
            set
            {
                if (_versionRegistro != value)
                {
                    _versionRegistro = value;
                    OnPropertyChanged("VersionRegistro");
                }
            }
        }
        private byte[] _versionRegistro;
    
        [DataMember]
        public bool EsAsignado
        {
            get { return _esAsignado; }
            set
            {
                if (_esAsignado != value)
                {
                    _esAsignado = value;
                    OnPropertyChanged("EsAsignado");
                }
            }
        }
        private bool _esAsignado;
    
        [DataMember]
        public Nullable<int> VersionOrden
        {
            get { return _versionOrden; }
            set
            {
                if (_versionOrden != value)
                {
                    _versionOrden = value;
                    OnPropertyChanged("VersionOrden");
                }
            }
        }
        private Nullable<int> _versionOrden;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public EstatusOrden EstatusOrden
        {
            get { return _estatusOrden; }
            set
            {
                if (!ReferenceEquals(_estatusOrden, value))
                {
                    var previousValue = _estatusOrden;
                    _estatusOrden = value;
                    FixupEstatusOrden(previousValue);
                    OnNavigationPropertyChanged("EstatusOrden");
                }
            }
        }
        private EstatusOrden _estatusOrden;
    
        [DataMember]
        public Proyecto Proyecto
        {
            get { return _proyecto; }
            set
            {
                if (!ReferenceEquals(_proyecto, value))
                {
                    var previousValue = _proyecto;
                    _proyecto = value;
                    FixupProyecto(previousValue);
                    OnNavigationPropertyChanged("Proyecto");
                }
            }
        }
        private Proyecto _proyecto;
    
        [DataMember]
        public Taller Taller
        {
            get { return _taller; }
            set
            {
                if (!ReferenceEquals(_taller, value))
                {
                    var previousValue = _taller;
                    _taller = value;
                    FixupTaller(previousValue);
                    OnNavigationPropertyChanged("Taller");
                }
            }
        }
        private Taller _taller;
    
        [DataMember]
        public TrackableCollection<OrdenTrabajoEspecialSpool> OrdenTrabajoEspecialSpool
        {
            get
            {
                if (_ordenTrabajoEspecialSpool == null)
                {
                    _ordenTrabajoEspecialSpool = new TrackableCollection<OrdenTrabajoEspecialSpool>();
                    _ordenTrabajoEspecialSpool.CollectionChanged += FixupOrdenTrabajoEspecialSpool;
                }
                return _ordenTrabajoEspecialSpool;
            }
            set
            {
                if (!ReferenceEquals(_ordenTrabajoEspecialSpool, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_ordenTrabajoEspecialSpool != null)
                    {
                        _ordenTrabajoEspecialSpool.CollectionChanged -= FixupOrdenTrabajoEspecialSpool;
                    }
                    _ordenTrabajoEspecialSpool = value;
                    if (_ordenTrabajoEspecialSpool != null)
                    {
                        _ordenTrabajoEspecialSpool.CollectionChanged += FixupOrdenTrabajoEspecialSpool;
                    }
                    OnNavigationPropertyChanged("OrdenTrabajoEspecialSpool");
                }
            }
        }
        private TrackableCollection<OrdenTrabajoEspecialSpool> _ordenTrabajoEspecialSpool;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
    	public void OnDeserializedMethod(StreamingContext context)
    	{
    		IsDeserializing = false;
    		ChangeTracker.ChangeTrackingEnabled = true;
    			if (_ordenTrabajoEspecialSpool != null)
    		{
    			_ordenTrabajoEspecialSpool.CollectionChanged -= FixupOrdenTrabajoEspecialSpool;
    			_ordenTrabajoEspecialSpool.CollectionChanged += FixupOrdenTrabajoEspecialSpool;
    			}
    		}
    
    
        protected virtual void ClearNavigationProperties()
        {
            EstatusOrden = null;
            Proyecto = null;
            Taller = null;
            OrdenTrabajoEspecialSpool.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupEstatusOrden(EstatusOrden previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.OrdenTrabajoEspecial.Contains(this))
            {
                previousValue.OrdenTrabajoEspecial.Remove(this);
            }
    
            if (EstatusOrden != null)
            {
                if (!EstatusOrden.OrdenTrabajoEspecial.Contains(this))
                {
                    EstatusOrden.OrdenTrabajoEspecial.Add(this);
                }
    
                EstatusOrdenID = EstatusOrden.EstatusOrdenID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("EstatusOrden")
                    && (ChangeTracker.OriginalValues["EstatusOrden"] == EstatusOrden))
                {
                    ChangeTracker.OriginalValues.Remove("EstatusOrden");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("EstatusOrden", previousValue);
                }
                if (EstatusOrden != null && !EstatusOrden.ChangeTracker.ChangeTrackingEnabled)
                {
                    EstatusOrden.StartTracking();
                }
            }
        }
    
        private void FixupProyecto(Proyecto previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.OrdenTrabajoEspecial.Contains(this))
            {
                previousValue.OrdenTrabajoEspecial.Remove(this);
            }
    
            if (Proyecto != null)
            {
                if (!Proyecto.OrdenTrabajoEspecial.Contains(this))
                {
                    Proyecto.OrdenTrabajoEspecial.Add(this);
                }
    
                ProyectoID = Proyecto.ProyectoID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Proyecto")
                    && (ChangeTracker.OriginalValues["Proyecto"] == Proyecto))
                {
                    ChangeTracker.OriginalValues.Remove("Proyecto");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Proyecto", previousValue);
                }
                if (Proyecto != null && !Proyecto.ChangeTracker.ChangeTrackingEnabled)
                {
                    Proyecto.StartTracking();
                }
            }
        }
    
        private void FixupTaller(Taller previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.OrdenTrabajoEspecial.Contains(this))
            {
                previousValue.OrdenTrabajoEspecial.Remove(this);
            }
    
            if (Taller != null)
            {
                if (!Taller.OrdenTrabajoEspecial.Contains(this))
                {
                    Taller.OrdenTrabajoEspecial.Add(this);
                }
    
                TallerID = Taller.TallerID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Taller")
                    && (ChangeTracker.OriginalValues["Taller"] == Taller))
                {
                    ChangeTracker.OriginalValues.Remove("Taller");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Taller", previousValue);
                }
                if (Taller != null && !Taller.ChangeTracker.ChangeTrackingEnabled)
                {
                    Taller.StartTracking();
                }
            }
        }
    
        private void FixupOrdenTrabajoEspecialSpool(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (OrdenTrabajoEspecialSpool item in e.NewItems)
                {
                    item.OrdenTrabajoEspecial = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("OrdenTrabajoEspecialSpool", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (OrdenTrabajoEspecialSpool item in e.OldItems)
                {
                    if (ReferenceEquals(item.OrdenTrabajoEspecial, this))
                    {
                        item.OrdenTrabajoEspecial = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("OrdenTrabajoEspecialSpool", item);
                    }
                }
            }
        }

        #endregion

    }
}
