//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SAM.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(NumeroUnicoMovimiento))]
    [Serializable]
    public partial class TipoMovimiento: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int TipoMovimientoID
        {
            get { return _tipoMovimientoID; }
            set
            {
                if (_tipoMovimientoID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'TipoMovimientoID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _tipoMovimientoID = value;
                    OnPropertyChanged("TipoMovimientoID");
                }
            }
        }
        private int _tipoMovimientoID;
    
        [DataMember]
        public bool EsEntrada
        {
            get { return _esEntrada; }
            set
            {
                if (_esEntrada != value)
                {
                    _esEntrada = value;
                    OnPropertyChanged("EsEntrada");
                }
            }
        }
        private bool _esEntrada;
    
        [DataMember]
        public string Nombre
        {
            get { return _nombre; }
            set
            {
                if (_nombre != value)
                {
                    _nombre = value;
                    OnPropertyChanged("Nombre");
                }
            }
        }
        private string _nombre;
    
        [DataMember]
        public string Descripcion
        {
            get { return _descripcion; }
            set
            {
                if (_descripcion != value)
                {
                    _descripcion = value;
                    OnPropertyChanged("Descripcion");
                }
            }
        }
        private string _descripcion;
    
        [DataMember]
        public Nullable<System.Guid> UsuarioModifica
        {
            get { return _usuarioModifica; }
            set
            {
                if (_usuarioModifica != value)
                {
                    _usuarioModifica = value;
                    OnPropertyChanged("UsuarioModifica");
                }
            }
        }
        private Nullable<System.Guid> _usuarioModifica;
    
        [DataMember]
        public Nullable<System.DateTime> FechaModificacion
        {
            get { return _fechaModificacion; }
            set
            {
                if (_fechaModificacion != value)
                {
                    _fechaModificacion = value;
                    OnPropertyChanged("FechaModificacion");
                }
            }
        }
        private Nullable<System.DateTime> _fechaModificacion;
    
        [DataMember]
        public byte[] VersionRegistro
        {
            get { return _versionRegistro; }
            set
            {
                if (_versionRegistro != value)
                {
                    ChangeTracker.RecordOriginalValue("VersionRegistro", _versionRegistro);
                    _versionRegistro = value;
                    OnPropertyChanged("VersionRegistro");
                }
            }
        }
        private byte[] _versionRegistro;
    
        [DataMember]
        public string NombreIngles
        {
            get { return _nombreIngles; }
            set
            {
                if (_nombreIngles != value)
                {
                    _nombreIngles = value;
                    OnPropertyChanged("NombreIngles");
                }
            }
        }
        private string _nombreIngles;
    
        [DataMember]
        public bool EsTransferenciaProcesos
        {
            get { return _esTransferenciaProcesos; }
            set
            {
                if (_esTransferenciaProcesos != value)
                {
                    _esTransferenciaProcesos = value;
                    OnPropertyChanged("EsTransferenciaProcesos");
                }
            }
        }
        private bool _esTransferenciaProcesos;
    
        [DataMember]
        public bool ApareceEnSaldos
        {
            get { return _apareceEnSaldos; }
            set
            {
                if (_apareceEnSaldos != value)
                {
                    _apareceEnSaldos = value;
                    OnPropertyChanged("ApareceEnSaldos");
                }
            }
        }
        private bool _apareceEnSaldos;
    
        [DataMember]
        public bool DisponibleMovimientosUI
        {
            get { return _disponibleMovimientosUI; }
            set
            {
                if (_disponibleMovimientosUI != value)
                {
                    _disponibleMovimientosUI = value;
                    OnPropertyChanged("DisponibleMovimientosUI");
                }
            }
        }
        private bool _disponibleMovimientosUI;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<NumeroUnicoMovimiento> NumeroUnicoMovimiento
        {
            get
            {
                if (_numeroUnicoMovimiento == null)
                {
                    _numeroUnicoMovimiento = new TrackableCollection<NumeroUnicoMovimiento>();
                    _numeroUnicoMovimiento.CollectionChanged += FixupNumeroUnicoMovimiento;
                }
                return _numeroUnicoMovimiento;
            }
            set
            {
                if (!ReferenceEquals(_numeroUnicoMovimiento, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_numeroUnicoMovimiento != null)
                    {
                        _numeroUnicoMovimiento.CollectionChanged -= FixupNumeroUnicoMovimiento;
                    }
                    _numeroUnicoMovimiento = value;
                    if (_numeroUnicoMovimiento != null)
                    {
                        _numeroUnicoMovimiento.CollectionChanged += FixupNumeroUnicoMovimiento;
                    }
                    OnNavigationPropertyChanged("NumeroUnicoMovimiento");
                }
            }
        }
        private TrackableCollection<NumeroUnicoMovimiento> _numeroUnicoMovimiento;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
    	public void OnDeserializedMethod(StreamingContext context)
    	{
    		IsDeserializing = false;
    		ChangeTracker.ChangeTrackingEnabled = true;
    			if (_numeroUnicoMovimiento != null)
    		{
    			_numeroUnicoMovimiento.CollectionChanged -= FixupNumeroUnicoMovimiento;
    			_numeroUnicoMovimiento.CollectionChanged += FixupNumeroUnicoMovimiento;
    			}
    		}
    
    
        protected virtual void ClearNavigationProperties()
        {
            NumeroUnicoMovimiento.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupNumeroUnicoMovimiento(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (NumeroUnicoMovimiento item in e.NewItems)
                {
                    item.TipoMovimiento = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("NumeroUnicoMovimiento", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (NumeroUnicoMovimiento item in e.OldItems)
                {
                    if (ReferenceEquals(item.TipoMovimiento, this))
                    {
                        item.TipoMovimiento = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("NumeroUnicoMovimiento", item);
                    }
                }
            }
        }

        #endregion

    }
}
