Insert into CampoSeguimientoJunta (ModuloSeguimientoJuntaID,Nombre,NombreIngles,OrdenUI,NombreControlUI,NombreColumnaSp,DataFormat,CssColumnaUI,UsuarioModifica,FechaModificacion,AnchoUI) values ('17','Familia Acero 1','Family of steel 1','18','','GeneralFamiliaAcero1','','',NULL,NULL,'125')
Insert into CampoSeguimientoJunta (ModuloSeguimientoJuntaID,Nombre,NombreIngles,OrdenUI,NombreControlUI,NombreColumnaSp,DataFormat,CssColumnaUI,UsuarioModifica,FechaModificacion,AnchoUI) values ('17','Familia Material 1','Family of material 1','19','','GeneralFamiliaMaterial1','','',NULL,NULL,'125')
Insert into CampoSeguimientoJunta (ModuloSeguimientoJuntaID,Nombre,NombreIngles,OrdenUI,NombreControlUI,NombreColumnaSp,DataFormat,CssColumnaUI,UsuarioModifica,FechaModificacion,AnchoUI) values ('17','Familia Acero 2','Family of steel 2','20','','GeneralFamiliaAcero2','','',NULL,NULL,'125')
Insert into CampoSeguimientoJunta (ModuloSeguimientoJuntaID,Nombre,NombreIngles,OrdenUI,NombreControlUI,NombreColumnaSp,DataFormat,CssColumnaUI,UsuarioModifica,FechaModificacion,AnchoUI) values ('17','Familia Material 2','Family of material 2','21','','GeneralFamiliaMaterial2','','',NULL,NULL,'125')
Insert into CampoSeguimientoJunta (ModuloSeguimientoJuntaID,Nombre,NombreIngles,OrdenUI,NombreControlUI,NombreColumnaSp,DataFormat,CssColumnaUI,UsuarioModifica,FechaModificacion,AnchoUI) values ('17','Porcentaje Pnd','NDT %','22','','GeneralPorcentajePnd','','',NULL,NULL,'125')
Insert into CampoSeguimientoJunta (ModuloSeguimientoJuntaID,Nombre,NombreIngles,OrdenUI,NombreControlUI,NombreColumnaSp,DataFormat,CssColumnaUI,UsuarioModifica,FechaModificacion,AnchoUI) values ('17','Especificacion','Specification','23','','GeneralEspecificacion','','',NULL,NULL,'125')
Insert into CampoSeguimientoJunta (ModuloSeguimientoJuntaID,Nombre,NombreIngles,OrdenUI,NombreControlUI,NombreColumnaSp,DataFormat,CssColumnaUI,UsuarioModifica,FechaModificacion,AnchoUI) values ('17','Diam Mat 1','Diam Mat 1','24','','GeneralDiamMat1','','',NULL,NULL,'125')
Insert into CampoSeguimientoJunta (ModuloSeguimientoJuntaID,Nombre,NombreIngles,OrdenUI,NombreControlUI,NombreColumnaSp,DataFormat,CssColumnaUI,UsuarioModifica,FechaModificacion,AnchoUI) values ('17','Esp Mat 1','Spec Mat 1','25','','GeneralEspMat1','','',NULL,NULL,'125')
Insert into CampoSeguimientoJunta (ModuloSeguimientoJuntaID,Nombre,NombreIngles,OrdenUI,NombreControlUI,NombreColumnaSp,DataFormat,CssColumnaUI,UsuarioModifica,FechaModificacion,AnchoUI) values ('17','Diam Mat 2','Diam Mat 2','26','','GeneralDiamMat2','','',NULL,NULL,'125')
Insert into CampoSeguimientoJunta (ModuloSeguimientoJuntaID,Nombre,NombreIngles,OrdenUI,NombreControlUI,NombreColumnaSp,DataFormat,CssColumnaUI,UsuarioModifica,FechaModificacion,AnchoUI) values ('17','Esp Mat 2','Spec Mat 2','27','','GeneralEspMat2','','',NULL,NULL,'125')
Insert into CampoSeguimientoJunta (ModuloSeguimientoJuntaID,Nombre,NombreIngles,OrdenUI,NombreControlUI,NombreColumnaSp,DataFormat,CssColumnaUI,UsuarioModifica,FechaModificacion,AnchoUI) values ('17','Peqs','Peqs','17','','GeneralPeqs','','',NULL,NULL,'125')
Insert into CampoSeguimientoJunta (ModuloSeguimientoJuntaID,Nombre,NombreIngles,OrdenUI,NombreControlUI,NombreColumnaSp,DataFormat,CssColumnaUI,UsuarioModifica,FechaModificacion,AnchoUI) values ('1','Ced Mat 1','Schedule Material 1','26','','ArmadoCedMat1','','',NULL,NULL,'125')
Insert into CampoSeguimientoJunta (ModuloSeguimientoJuntaID,Nombre,NombreIngles,OrdenUI,NombreControlUI,NombreColumnaSp,DataFormat,CssColumnaUI,UsuarioModifica,FechaModificacion,AnchoUI) values ('1','Ced Mat 2','Schedule Material 2','29','','ArmadoCedMat2','','',NULL,NULL,'125')

Update CampoSeguimientoJunta set Nombre='Ultima Captura', NombreIngles='Last Capture' where CampoSeguimientoJuntaID=136
select * from CampoSeguimientoJunta