ALTER TABLE JuntaSpool
ADD	FabClas NVARCHAR(150) NULL

ALTER TABLE JuntaSpool
ADD	Campo2 NVARCHAR(150) NULL

ALTER TABLE JuntaSpool
ADD	Campo3 NVARCHAR(150) NULL

ALTER TABLE JuntaSpool
ADD	Campo4 NVARCHAR(150) NULL

ALTER TABLE JuntaSpool
ADD	Campo5 NVARCHAR(150) NULL