
-------------------------------------------------------------------------
DECLARE @agrPNDID INT, @agrRepID INT , @agrSopID INT
SET @agrPNDID = (SELECT ModuloSeguimientoJuntaID FROM ModuloSeguimientoJunta WHERE Nombre = 'Agrupadores PND')
SET @agrRepID = (SELECT ModuloSeguimientoJuntaID FROM ModuloSeguimientoJunta WHERE Nombre = 'Agrupadores Reparaciones')
SET @agrSopID = (SELECT ModuloSeguimientoJuntaID FROM ModuloSeguimientoJunta WHERE Nombre = 'Agrupadores Soportes')

--INSERT AGRUPADORES PND
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrPNDID, 'Último Proceso', 'Last Process', 1, 'litAgrupadoresPNDUltimoProceso', 'AgrupadoresPNDUltimoProceso', 125 , '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrPNDID, 'Area Grupo', 'Group Area', 2, 'litAgrupadoresPNDAreaGrupo', 'AgrupadoresPNDAreaGrupo', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrPNDID, 'Kgs Grupo', 'Kgs Group', 3, 'litAgrupadoresPNDKgsGrupo', 'AgrupadoresPNDKgsGrupo', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrPNDID, 'Diam Grupo', 'Diam Group', 4, 'litAgrupadoresPNDDiamGrupo', 'AgrupadoresPNDDiamGrupo', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrPNDID, 'PEQ Grupo', 'PEQ Group', 5, 'litAgrupadoresPNDPEQGrupo', 'AgrupadoresPNDPEQGrupo', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrPNDID, 'Sistema Pintura Final', 'Final Paint System', 6, 'litAgrupadoresPNDSistemaPinturaFinal', 'AgrupadoresPNDSistemaPinturaFinal', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrPNDID, 'Paint/NoPaint', 'Paint/NoPaint', 7, 'litAgrupadoresPNDPainNoPaint', 'AgrupadoresPNDPaintNoPaint', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrPNDID, 'Diametro Promedio', 'Average Diameter', 8, 'litAgrupadoresPNDDiametroPromedio', 'AgrupadoresPNDDiametroPromedio', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrPNDID, 'PaintLine', 'PaintLine', 9, 'litAgrupadoresPNDPaintLine', 'AgrupadoresPNDPaintLine', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrPNDID, 'Area EQ', 'EQ Area', 10, 'litAgrupadoresPNDAreaEQ', 'AgrupadoresPNDAreaEQ', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrPNDID, 'Inox/NoInox', 'Inox/NoInox', 11, 'litAgrupadoresPNDInoxNoInox', 'AgrupadoresPNDInoxNoInox', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrPNDID, 'Clasif Inox', 'Clasif Inox', 12, 'litAgrupadoresPNDClasifInox', 'AgrupadoresPNDClasifInox', 125, '', '')

--INSERT AGRUPADORES REPARACIONES
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrRepID, 'Último Proceso', 'Last Process', 1, 'litAgrupadoresRepUltimoProceso', 'AgrupadoresRepUltimoProceso', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrRepID, 'Area Grupo', 'Group Area', 2, 'litAgrupadoresRepAreaGrupo', 'AgrupadoresRepAreaGrupo', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrRepID, 'Kgs Grupo', 'Kgs Group', 3, 'litAgrupadoresRepKgsGrupo', 'AgrupadoresRepKgsGrupo', 125 , '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrRepID, 'Diam Grupo', 'Diam Group', 4, 'litAgrupadoresRepDiamGrupo', 'AgrupadoresRepDiamGrupo', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrRepID, 'PEQ Grupo', 'PEQ Group', 5, 'litAgrupadoresRepPEQGrupo', 'AgrupadoresRepPEQGrupo', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrRepID, 'Sistema Pintura Final', 'Final Paint System', 6, 'litAgrupadoresRepSistemaPinturaFinal', 'AgrupadoresRepSistemaPinturaFinal', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrRepID, 'Paint/NoPaint', 'Paint/NoPaint', 7, 'litAgrupadoresRepPainNoPaint', 'AgrupadoresRepPaintNoPaint', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrRepID, 'Diametro Promedio', 'Average Diameter', 8, 'litAgrupadoresRepDiametroPromedio', 'AgrupadoresRepDiametroPromedio', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrRepID, 'PaintLine', 'PaintLine', 9, 'litAgrupadoresRepPaintLine', 'AgrupadoresRepPaintLine', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrRepID, 'Area EQ', 'EQ Area', 10, 'litAgrupadoresRepAreaEQ', 'AgrupadoresRepAreaEQ', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrRepID, 'Inox/NoInox', 'Inox/NoInox', 11, 'litAgrupadoresRepInoxNoInox', 'AgrupadoresRepInoxNoInox', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrRepID, 'Clasif Inox', 'Clasif Inox', 12, 'litAgrupadoresRepClasifInox', 'AgrupadoresRepClasifInox', 125, '', '')

--INSERT AGRUPADORES SOPORTES
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrSopID, 'Último Proceso', 'Last Process', 1, 'litAgrupadoresSopUltimoProceso', 'AgrupadoresSopUltimoProceso', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrSopID, 'Area Grupo', 'Group Area', 2, 'litAgrupadoresSopAreaGrupo', 'AgrupadoresSopAreaGrupo', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrSopID, 'Kgs Grupo', 'Kgs Group', 3, 'litAgrupadoresSopKgsGrupo', 'AgrupadoresSopKgsGrupo', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrSopID, 'Diam Grupo', 'Diam Group', 4, 'litAgrupadoresSopDiamGrupo', 'AgrupadoresSopDiamGrupo', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrSopID, 'PEQ Grupo', 'PEQ Group', 5, 'litAgrupadoresSopPEQGrupo', 'AgrupadoresSopPEQGrupo', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrSopID, 'Sistema Pintura Final', 'Final Paint System', 6, 'litAgrupadoresSopSistemaPinturaFinal', 'AgrupadoresSopSistemaPinturaFinal', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrSopID, 'Paint/NoPaint', 'Paint/NoPaint', 7, 'litAgrupadoresSopPainNoPaint', 'AgrupadoresSopPaintNoPaint', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrSopID, 'Diametro Promedio', 'Average Diameter', 8, 'litAgrupadoresSopDiametroPromedio', 'AgrupadoresSopDiametroPromedio', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrSopID, 'PaintLine', 'PaintLine', 9, 'litAgrupadoresSopPaintLine', 'AgrupadoresSopPaintLine', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrSopID, 'Area EQ', 'EQ Area', 10, 'litAgrupadoresSopAreaEQ', 'AgrupadoresSopAreaEQ', 125, '','')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrSopID, 'Inox/NoInox', 'Inox/NoInox', 11, 'litAgrupadoresSopInoxNoInox', 'AgrupadoresSopInoxNoInox', 125, '', '')
INSERT INTO CampoSeguimientoJunta (ModuloSeguimientoJuntaID, Nombre, NombreIngles, OrdenUI, NombreControlUI, NombreColumnaSp,AnchoUI, DataFormat, CssColumnaUI)
	VALUES(@agrSopID, 'Clasif Inox', 'Clasif Inox', 12, 'litAgrupadoresSopClasifInox', 'AgrupadoresSopClasifInox', 125, '', '')