--INSERTAR CUADRANTES PARA BASE DE DATOS DE PRODUCCION
GO
--ALTAMIRA
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'1A')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'1B')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'1C')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'1D')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'1E')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'1F')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'2A')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'2B')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'2C')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'2D')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'2E')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'2F')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'3A')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'3B')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'3C')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'3D')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'3E')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'3F')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'4A')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'4B')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'4C')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'4D')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'4E')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'4F')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'5A')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'5B')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'5C')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'5D')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'5E')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'5F')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'6A')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'6B')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'6C')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'6D')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'6E')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'6F')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'Nave pintura')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'Pintura exterior')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'Embarcado')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(6,'tecnia')
--
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(1,'Comdistral')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(2,'Veracruz')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(3,'Bay-Corpus Christi')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(4,'Bay Housto')
INSERT INTO [dbo].[Cuadrante]([PatioID],[Nombre]) VALUES(5,'Bay Montana')
GO


