

CREATE TABLE dbo.SpoolsDeleted(
	SpoolID int NOT NULL,
	ProyectoID int NOT NULL,
	FamiliaAcero1ID int NULL,
	FamiliaAcero2ID int NULL,
	Nombre nvarchar(50) NOT NULL,
	Dibujo nvarchar(50) NOT NULL,
	Especificacion nvarchar(15) NULL,
	Cedula nvarchar(10) NULL,
	Pdis decimal(10, 4) NULL,
	DiametroPlano decimal(10, 4) NULL,
	Peso decimal(7, 2) NULL,
	Area decimal(7, 2) NULL,
	PorcentajePnd int NULL,
	RequierePwht bit NOT NULL,
	PendienteDocumental bit NOT NULL,
	AprobadoParaCruce bit NOT NULL,
	Prioridad int NULL,
	Revision nvarchar(10) NULL,
	RevisiomCliente nvarchar(10) NULL,
	Segmento1 nvarchar(20) NULL,
	Segmento2 nvarchar(20) NULL,
	Segmento3 nvarchar(20) NULL,
	Segmento4 nvarchar(20) NULL,
	Segmento5 nvarchar(20) NULL,
	Segmento6 nvarchar(20) NULL,
	Segmento7 nvarchar(20) NULL,
	UsuarioModifica uniqueidentifier NULL,
	FechaModificacion datetime NULL,
	VersionRegistro timestamp NOT NULL,
	SistemaPintura nvarchar(50) NULL,
	ColorPintura nvarchar(50) NULL,
	CodigoPintura nvarchar(50) NULL,
	FechaEtiqueta datetime NULL,
	NumeroEtiqueta nvarchar(20) NULL,
	Campo1 nvarchar(100) NULL,
	Campo2 nvarchar(100) NULL,
	Campo3 nvarchar(100) NULL,
	Campo4 nvarchar(100) NULL,
	Campo5 nvarchar(100) NULL,
	DiametroMayor decimal(10, 4) NULL,
	FechaImportacion datetime NULL,
 CONSTRAINT PK_SpoolsDeleted PRIMARY KEY(SpoolID))



