ALTER TABLE Spool
ADD UltimoProceso  NVARCHAR(500) NULL

ALTER TABLE Spool
ADD AreaGrupo  NVARCHAR(500) NULL

ALTER TABLE Spool
ADD KgsGrupo  NVARCHAR(500) NULL

ALTER TABLE Spool
ADD DiamGrupo  NVARCHAR(500) NULL

ALTER TABLE Spool
ADD PeqGrupo  NVARCHAR(500) NULL

ALTER TABLE Spool
ADD SistemaPinturaFinal  NVARCHAR(500) NULL

ALTER TABLE Spool
ADD Paint  NVARCHAR(500) NULL

ALTER TABLE Spool
ADD DiametroPromedio  NVARCHAR(500) NULL

ALTER TABLE Spool
ADD PaintLine  NVARCHAR(500) NULL

ALTER TABLE Spool
ADD AreaEq  NVARCHAR(500) NULL

ALTER TABLE Spool
ADD Inox  NVARCHAR(500) NULL

ALTER TABLE Spool
ADD ClasifInox  NVARCHAR(500) NULL
