//namespace global
if (!Sam) {
    var Sam = {};
}

Sam.MensajesUI = function (num, params) {
    var s = num + "";
    s = s.pad(0, 3);
    var l = Sam.Utilerias.ObtenCookie("Culture");
    var msg = Sam.MensajesUI[l][s];
    if (params) {
        msg = msg.format($.isArray(params) ? params : [params]);
    }
    return msg;
};

Sam.MensajesUI["en-US"] = {};
Sam.MensajesUI["es-MX"] = {};

Sam.MensajesUI["es-MX"] = {
    "001": "¿Está seguro que desea eliminar el registro seleccionado?",
    "002": "¿Está seguro que desea eliminar la orden de trabajo {0}?",
    "003": "¿Esta seguro que desea cortar la junta seleccionada?",
    "004": "¿Está seguro que deseal eliminar el spool {0} de la orden de trabajo?",
    "005": "Se procederá a incluir los materiales y/o juntas faltantes en en número de control {0}.\nSi la orden de trabajo ya está siendo fabricada no olvide informar a taller. ¿Desea continuar?",
    "006": "¿Está seguro que desea cancelar el despacho seleccionado?",
    "007": "Al menos un spool debe estar seleccionado",
    "008": "¿Está seguro que desea cancelar el corte seleccionado?",
    "009": "Al menos un Número Unico debe estar seleccionado.",
    "010": "Al menos una Junta debe estar seleccionada.",
    "011": "¿Está seguro que desea cancelar el armado seleccionado?",
    "012": "¿Está usted seguro que desea aprobar el destajo seleccionado?",
    "013": "Al recalcular el destajo perderá los valores introducidos manualmente.\n¿Desea continuar?",
    "014": "¿Está seguro que desea cancelar la soldadura seleccionada?",
    "015": "¿Está seguro que desea eliminar la junta seleccionada del destajo?\nLa acción no se podrá revertir.",
    "016": "Comentarios de armado",
    "017": "Comentarios de soldadura",
    "018": "Comentarios partida",
    "019": "¿Desea cerrar el periodo seleccionado?\nEsta acción no se podrá revertir.",
    "020": "¿La Cédula no coincide con la descripción del Item Code, desea continuar?",
    "021": "¿Está usted seguro que desea importar las Tablas de Destajo del proyecto? Todos los registros de valores de destajos previamente guardados se eliminarán para importar los nuevos.",
    "022": "¿Está usted seguro que desea actualizar los valores de Peq, KgT y Espesores del proyecto? Una vez actualizados no se podrá revertir la información.",
    "023": "¿Está usted seguro que desea eliminar el movimiento seleccionado?",
    "024": "¿Está usted seguro que desea eliminar el corte detalle seleccionado?",
    "025": "Para esta operacion solo debe de seleccionar un material",
    "026": "Para esta operacion debe de seleccionar dos materiales",
    "027": "Seleccione solo el material pendiente por homologar",
    "028": "Seleccione solo el material existente",
    "029": "¿Está usted seguro que desea eliminar el congelado parcial seleccionado?",
    "030": "¿Está seguro que desea eliminar el reporte seleccionado?",
    "031": "El número único cuenta con material congelado. ¿Desea que este material sea traspasado a otro número único para proceder con el cambio de estatus?",
    "032": "Una o más de las fechas registradas son menores que las fechas de Armado , ¿Desea modificar las fechas de Armado?",
    "033": "Cambiar fechas de armado",
    "034": "Los números de control y juntas{0}\n no se pueden guardar porque tiene fecha incorrecta, ¿Desea guardar el reporte para las demás juntas?",
    "035": "Los números de control {0} no se pueden guardar porque tienen fecha incorrecta, ¿Desea guardar el reporte para los demás números de control?",
    "036": "El reporte no se puede guardar ya que hay un error con las fechas respecto a las de {0}",
    "037": "El reporte no se puede guardar ya que ninguna de las fechas de Armado puede ser mayor que las fechas de Soldadura",
    "038": "Hay un problema con la fecha de {0}, ya que no puede ser menor que la requisición de pintura",
    "039": "Los spools y juntas{0}\n no se pueden guardar porque tiene fecha incorrecta, ¿Desea guardar el reporte para las demás juntas?",
    "040": "Las fechas de Armado no pueden ser mayores que las fechas de Soldadura",
    "041": "La fecha del reporte debe ser mayor o igual a la del proceso",
    "042": "Las fechas son requeridas",
    "043": "Cambiar fechas de soldadura",
    "044": "Una o más de las fechas registradas son menores que las fechas de Soldadura, ¿Desea modificar las fechas de Soldadura?",
    "045": "La fecha registrada es menor que las fechas de Inspección Visual, ¿Desea modificar las fechas de Inspección Visual?",
    "046": "Cambiar fechas de Inspección Visual",
    "047": "Cambiar fechas de Requisición",
    "048": "Una o más de las fechas registradas es menor que la fecha de Requisición, ¿Desea modificar la fecha de Requisición?",
    "049": "Las fechas capturadas no pueden ser menores a las fechas del proceso",
    "050": "¿Está usted seguro que desea actualizar el valor de la Estación para el grupo de juntas?",
    "051": "La fecha del reporte es mayor a la fecha del reporte de soldadura, ¿Desea proceder?",
    "052": "La fecha del reporte es menor a la fecha del reporte de armado, ¿Desea proceder?",
    "053": "La fecha del proceso es menor a la fecha del proceso anterior de las juntas {0}",
    "054": "La fecha del reporte es menor a la fecha del reporte del proceso anterior de las juntas {0}, ¿Desea proceder?",
    "055": "La fecha del proceso es menor a la fecha del proceso anterior de {0}",
    "056": "La fecha del reporte es menor a la fecha del reporte del proceso anterior de {0}, ¿Desea proceder?",
    "057": "La fecha del reporte es mayor a la fecha del reporte de IV, ¿Desea proceder?",
    "058": "La fecha del reporte es menor a la fecha del reporte del proceso anterior, ¿Desea proceder?",
    "059": "La fecha del proceso es menor a la fecha del proceso anterior de los números de control {0}",
    "060": "La fecha de la prueba debe ser mayor o igual a la del proceso de requisición de los siguientes números de control: {0}"
};

Sam.MensajesUI["en-US"] = {
    "001": "Are you sure you want to delete the selected record?",
    "002": "Are you sure you want to delete job order {0}?",
    "003": "Are you sure you want to cut the selected weld?",
    "004": "Are you sure you want to delete spool {0} from the job order?",
    "005": "Missing materials and welds will be included in control number {0}.\nRemember to notify the shop about the change. Do you want to proceed?",
    "006": "Are you sure you want to cancel the selected dispatch?",
    "007": "At least one spool must be selected",
    "008": "Are you sure you want to cancel the selected cut?",
    "009": "At least one unique number must be selected.",
    "010": "At least one Joint must be selected.",
    "011": "Are you sure you want to cancel the selected fitting?",
    "012": "Are you sure you want to approve the selected employee payroll?",
    "013": "Upon recalculation manually entered values will be lost.\nDo you want to proceed?",
    "014": "Are you sure you want to cancel the selected welding?",
    "015": "Are you sure you want to delete the selected joint weld?\nThis action cannot be undone.",
    "016": "Fitting comments",
    "017": "Welding comments",
    "018": "Row comments",
    "019": "Do you want to close the selected payroll period?\nThis action cannot be undone.",
    "020": "Schedula and Item Code description have no relation, do you want to proceed?",
    "021": "Are you sure you want to import the project Piecework Tables? All records previously saved will be deleted to import the new values.",
    "022": "¿Are you sure you want to update the values Inch Eq, Kg´s and Ticknesses of the project? Once updated the information you wont be able to reverse the process.",
    "023": "¿Are you sure you want to delete selected movement?",
    "024": "¿Are you sure you want to delete selected detail of cut?",
    "025": "You are only allowed to select one material for this operation",
    "026": "You should select to materials for tis operation",
    "027": "Select only pending material to homologate",
    "028": "Select only existing material",
    "029": "Are you sure you want to delete selected partial allocated?",
    "030": "Are you sure you want to delete the selected report?",
    "031": "The unique number has allocated material. Do you want this material to be transferred to another unique number to proceed with the change of status?",
    "032": "One o more of the registered dates is lower than assembly dates, Do you want change the date of assembly report?",
    "033": "Change date of assembly",
    "034": "The control number and joint{0}\n can't be save because have wrong date, Do you want to save the report for the others joints?",
    "035": "The control number {0} can't be save because have wrong date, Do you want to save the report for the others control numbers?",
    "036": "The report can not be saved because there is an error with respect to the dates of {0} dates",
    "037": "The report can not be saved because no one of the Assembly dates can be greater than Welding dates",
    "038": "There's a problem with the {0} date because it can not be lower that paint requisition",
    "039": "The spools and joint{0}\n can't be save because have wrong date, Do you want to save the report for the others joints?",
    "040": "The Assembly dates can't be greater than Welding dates",
    "041": "The report date must be greater than process date",
    "042": "The dates are required",
    "043": "Change date of welding",
    "044": "One o more of the registered dates is lower than welding dates, Do you want change the date of welding report?",
    "045": "the registered date is lower than visual inspection dates, Do you want change the date of visual inspection report?",
    "046": "Change date of visual inspection",
    "047": "Change requisition date",
    "048": "One o more of the registered dates is lower than requisition date, Do you want change the date of requisition?",
    "049": "The current dates can't be lower than process dates",
    "050": "Are you sure you want to update the value of the Station for the group of joints?",
    "051": "The report date is greater than welding report date , Do you want to proceed?",
    "052": "The report date is lower than fitting report date , Do you want to proceed?",
    "053": "The process date is lower than previous process date of joints {0}",
    "054": "The report date is lower than previous process date of joints {0}, Do you want to proceed?",
    "055": "The process date is lower than previous process date of {0}",
    "056": "The report date is lower than previous report date of {0}, Do you want to proceed?",
    "057": "The report date is greater than VI report date , Do you want to proceed?",
    "058": "The report date is lower than previous report date, Do you want to proceed?",
    "059": "The process date is lower than previous process date of control numbers {0}",
    "060": "The test date must be greater or equal to the requisition process of the following control numbers: {0}"
};
