//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAM.BusinessLogic.Utilerias {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TitulosColumnaEstimacionSpool {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TitulosColumnaEstimacionSpool() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAM.BusinessLogic.Utilerias.TitulosColumnaEstimacionSpool", typeof(TitulosColumnaEstimacionSpool).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cédula.
        /// </summary>
        public static string Cedula {
            get {
                return ResourceManager.GetString("Cedula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embarcado.
        /// </summary>
        public static string Embarcado {
            get {
                return ResourceManager.GetString("Embarcado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberación dimensional.
        /// </summary>
        public static string InspeccionDimensional {
            get {
                return ResourceManager.GetString("InspeccionDimensional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero Control.
        /// </summary>
        public static string NumeroControl {
            get {
                return ResourceManager.GetString("NumeroControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDI.
        /// </summary>
        public static string PDI {
            get {
                return ResourceManager.GetString("PDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pintura.
        /// </summary>
        public static string Pintura {
            get {
                return ResourceManager.GetString("Pintura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spool.
        /// </summary>
        public static string Spool {
            get {
                return ResourceManager.GetString("Spool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkstatusSpoolId.
        /// </summary>
        public static string WorkstatusSpoolId {
            get {
                return ResourceManager.GetString("WorkstatusSpoolId", resourceCulture);
            }
        }
    }
}
